language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - PYTHONPATH=/home/travis/build/yhaidai/epam-python-winter-2021-final-project/department_app/ coverage run -m unittest discover department_app/tests
  - coverage report

