language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

before_script:
  export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - coverage run -m unittest discover department_app/tests
  - coverage report

